name: Terraform apply

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  apply:
    runs-on: self-hosted
    steps:
      - name: Apply
        run: | 
         git pull origin master
         terraform init
         terraform plan
         echo "Done!."
