name: Action Sample

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  print-stress-cpu:
    runs-on: self-hosted
    steps:
      - name: execute echo command
        run: stress --cpu 2 --timeout 10
