name: Action Sample

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  print-hello-world:
    runs-on: self-hosted
    steps:
      - name: execute echo command
        run: echo "Hello World!"
