name: Action Sample

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  print-stress-cpu_terraform_plan:
    runs-on: self-hosted
    steps:
      - name: execute stress command
        run: | 
         stress --cpu 2 --timeout 20
         terraform init
         terraform plan
         echo "Done."
